<?php
/**
* Implementation of hook_menu().
*/
function cesap_res_menu()
{

  $items['reservas/espacios-deportivos'] = array(
    'title' => 'Reservas de espacios deportivos',
    'page callback' => '_cesap_res_sports',
    'access arguments' => array('ezapp create appointment'),
    'type' => MENU_NORMAL_ITEM,
  );  

  return $items;
}

function _cesap_res_sports()
{
  drupal_add_js('https://cdn.jsdelivr.net/npm/vue/dist/vue.js', 'external');
  drupal_add_js('https://cdn.jsdelivr.net/npm/flatpickr', 'external');
  drupal_add_css('https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css', 'external');

  // return 'hola <input type="date">';
  return theme('cesap_res_page');
}


function cesap_res_theme(){

  return array(
    'cesap_res_page' => array(
      // template file name will be custom-page.tpl.php
      'template' => 'cesap-res--reservation',
    ),
  );
}